import turtle as t

timmy=t.Turtle()
timmy.pensize(6)
screen=t.Screen()
timmy.penup()
timmy.speed("fastest")
screen.screensize(400,300)
timmy.setpos(-300,200)

def kart_basma(x):
    if x=="1":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(50)
        timmy.sety(200)
        timmy.pendown()
        timmy.seth(270)
        timmy.forward(40)
        timmy.seth(90)
        timmy.forward(40)
        timmy.left(135)
        timmy.forward(20)
    elif x=="2":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(50)
        timmy.sety(200)
        timmy.pendown()
        timmy.seth(225)
        timmy.forward(20)
        timmy.right(180)
        timmy.forward(20)
        timmy.right(90)
        timmy.forward(20)
        timmy.seth(225)
        timmy.forward(40)
        timmy.seth(0)
        timmy.forward(30)
    elif x=="3":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(50)
        timmy.sety(200)
        timmy.pendown()
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(0)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
    elif x=="4":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.seth(235)
        timmy.forward(35)
        timmy.seth(0)
        timmy.forward(30)
        timmy.seth(180)
        timmy.forward(10)
        timmy.seth(270)
        timmy.forward(15)
    elif x=="5":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.forward(30)
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(0)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
    elif x=="6":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(40)
        timmy.seth(0)
        timmy.forward(30)
        timmy.seth(90)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
    elif x=="7":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.forward(35)
        timmy.seth(235)
        timmy.forward(50)
    elif x=="8":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(0)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(20)
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(90)
        timmy.forward(40)
    elif x=="9":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        for i in range(4):
            timmy.right(90)
            timmy.forward(20)
        timmy.seth(270)
        timmy.forward(40)
    elif x=="10":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(200)
        timmy.pendown()
        timmy.seth(270)
        timmy.forward(40)
        timmy.seth(90)
        timmy.forward(40)
        timmy.left(135)
        timmy.forward(20)
        timmy.penup()
        timmy.sety(160)
        timmy.seth(0)
        timmy.forward(30)
        timmy.pendown()
        timmy.forward(30)
        timmy.seth(90)
        timmy.forward(40)
        timmy.seth(180)
        timmy.forward(30)
        timmy.seth(270)
        timmy.forward(40)
    elif x=="J":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(140)
        timmy.pendown()
        timmy.write(x, font=("Aria",50,"normal"))
    elif x=="Q":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(140)
        timmy.pendown()
        timmy.write(x, font=("Aria",50,"normal"))
    elif x=="K":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(140)
        timmy.pendown()
        timmy.write(x, font=("Aria",50,"normal"))
    elif x=="A":
        timmy.penup()
        timmy.seth(0)
        timmy.forward(70)
        timmy.sety(140)
        timmy.pendown()
        timmy.write(x, font=("Aria",50,"normal"))

timmy.hideturtle()
screen.exitonclick()


"""timmy.penup()
        timmy.sety(100)
        timmy.seth(270)
        timmy.forward(70)
        timmy.pendown()"""
